force-app/main/default/objects/product_shop__c/product_shop__c.object-meta.xml
<CustomObject>
    <label>product shop</label>
    <nameField>
        <label>product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/product_shop__c/fields/category__c.field-meta.xml
<CustomField>
    <fullName>category__c</fullName>
    <label>category</label>
    <referenceTo>category__c</referenceTo>
    <relationshipLabel>products</relationshipLabel>
    <relationshipName>products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/product_shop__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/product_shop__c/fields/image__c.field-meta.xml
<CustomField>
    <fullName>image__c</fullName>
    <label>image</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/product_shop__c/fields/price__c.field-meta.xml
<CustomField>
    <fullName>price__c</fullName>
    <description>price of my product</description>
    <label>price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ProductController.cls
//import { ProductShopModel } from  '@salesforce/apex/ProductShopModel.ProductShopModel';
//const ProductShopModel = require ('model/ProductShopModel')
public with sharing class ProductController {
   
    @AuraEnabled
    public static product_shop__c[] getAllProducts() {

       // ProductShopService service = new ProductShopService(0);
       // product_shop__c[] shopService = service..getProducts();
       
       // product_shop__c[] shopService = ProductShopService.getProducts();
        //return shopService;

        return[
             SELECT
               Id,
                Name,
                Description__c,
                image__c,
                price__c
              
            FROM product_shop__c
           
            ORDER BY Name
            LIMIT 50
        ];


    }


    @AuraEnabled(cacheable=true scope='global')
    public static product_shop__c[] searchProducts(String searchTerm) {
     
        searchTerm = searchTerm.trim();
        if (searchTerm == '') {
            return getAllProducts();
        }
        
        searchTerm = '%' + searchTerm + '%';
  
        return [
            SELECT
               Id,
                Name,
                Description__c,
                image__c,
                price__c
              
            FROM product_shop__c
            WHERE Name LIKE :searchTerm
            WITH SECURITY_ENFORCED
            ORDER BY Name
         
        ];
    }

    @AuraEnabled
    public static void deleteProduct(ID productId) {

        list<product_shop__c> product = [SELECT Id FROM product_shop__c WHERE Id = :productId];
        delete product;
       




    }

    @AuraEnabled
    public static product_shop__c[] getCatFemme() {

       
        return[
            SELECT Id,Name,Description__c,category__c 
            FROM product_shop__c
            WHERE category__c='a0F7R00002XFa4nUAD'
          
            ORDER BY Name
            LIMIT 50
       ];
       




    }
    

    
}