force-app/main/default/objects/product_shop__c/product_shop__c.object-meta.xml
<CustomObject>
    <label>product shop</label>
    <nameField>
        <label>product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/product_shop__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/product_shop__c/fields/price__c.field-meta.xml
<CustomField>
    <fullName>price__c</fullName>
    <description>price of my product</description>
    <label>price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ProductManager.cls
@RestResource(urlMapping='/product_shop__c/*')
global with sharing class ProductManager {
      @HttpGet
    global static product_shop__c getAccount() {
        RestRequest request = RestContext.request;
        // grab the caseId from the end of the URL
        String productId = request.requestURI.substring(request.requestURI.lastIndexOf('/')+1);
        product_shop__c result = [ SELECT ID, Name, Description__c
                        FROM product_shop__c
                        WHERE Id = :productId];
        return result;
    }
    @HttpPost
    global static ID createProduct(String Name, String Description,
        Decimal price) {
        product_shop__c product = new product_shop__c(
            Name=Name,
            Description__c=Description,
            price__c=price);
        insert product;
        return product.Id;
    } 
    @HttpDelete
    global static void deleteProduct() {
        RestRequest request = RestContext.request;
        String productId = request.requestURI.substring(
            request.requestURI.lastIndexOf('/')+1);
        product_shop__c product = [SELECT Id FROM product_shop__c WHERE Id = :productId];
        delete product;
    }

    

}