force-app/main/default/objects/product_shop__c/product_shop__c.object-meta.xml
<CustomObject>
    <label>product shop</label>
    <nameField>
        <label>product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/product_shop__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/product_shop__c/fields/image__c.field-meta.xml
<CustomField>
    <fullName>image__c</fullName>
    <label>image</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/product_shop__c/fields/price__c.field-meta.xml
<CustomField>
    <fullName>price__c</fullName>
    <description>price of my product</description>
    <label>price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/productShopService.cls
public  with sharing class ProductShopService  {

   

   public ProductShopService() 
   {
      
   }

    @AuraEnabled
    public static product_shop__c[] getProducts() {

       return[
             SELECT
               Id,
                Name,
                Description__c,
                image__c,
                price__c
              
            FROM product_shop__c
           
            ORDER BY Name
            LIMIT 50
        ];



    }
}